language: node_js
node_js:
- 10
services:
- docker
env:
  global:
  - REACT_APP_API_BASE_URL=http://localhost:8080
  - PACT_BROKER_BASE_URL=https://albertowar.pactflow.io
  # PACT_BROKER_TOKEN is encrypted below
  - secure: "An7MXNT+EsXzjJrE+O0P84tM0fIs+mBtiOsuPdMFCkkuc20eQAJy2uxRu1QW0ARKIA15CVfqOneVRFeMjetwbaoyio+WaWJRzQL5wWKfC8EYl7vp6tIKuovrjPSsoQlDQ23PrUdi2K0a4EcaZpXV+TaAzPte2iZcGDPDcSAGoHsSn2UCDWSrWA4SsN8eCYpW5bM56yVrV5taVyvr1aStnreHPBmQJJvnADGyuEwB8qfN5HpBOCnmdz8ZZ7FWhPzKB9JfwfTNchQML+917CC09WEgKC9mKpQpkfzSPD4zy2TMhQcJxTkE/GZwbbn/XR498DOWFm3/qj0/xPqtH8zskSC1hIaAHiZIZwffqu8swmRce+kv3rx0lbzTGvdMlleX7caHzAvvv7dEos8Gqa40xPzqXWMzhCdzv08AW/9K+A6fEyVMY0jsPjNsDa9+6Jf2/WbZ/CpmXZYWu7vMq6f60orggXj1fLBdj7hlamuMwjceug1fuhqxw9afsvWP9CcyF4AN4h3tAyiVVwtxHQt2Nz3KRplOKHE2fwnSrVtZHoi/AW0lkHu6s3KdrjUmNVisINhb09eJjHFrvUnRFgMqGDizNim069TLhlxPabQAICUSAgo4SKickrdHmPkTyyaTSVY0JlmeZRu6WTJ9sNCLOUnbZz2krOQjo0S/oKxAt/E="
before_script:
  - docker pull pactfoundation/pact-cli:latest
script:
- make ci
